# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test

on:

  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'
      -
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  workflow_dispatch:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    env:
      EXANTE_ACCOUNT_ID: ${{ secrets.EXANTE_ACCOUNT_ID }}
      EXANTE_SERVER_ADDR: ${{ secrets.EXANTE_SERVER_ADDR }}
      EXANTE_CLIENT_ID: ${{ secrets.EXANTE_CLIENT_ID }}
      EXANTE_APP_ID: ${{ secrets.EXANTE_APP_ID }}
      EXANTE_SHARED_KEY: ${{ secrets.EXANTE_SHARED_KEY }}
      
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./http/

    - name: Test
      run: go test -v ./http/... -run TestBaseline
